### ISSUE TITLE
possible typo in nvram-user-sample.sh

### ISSUE THREAD

**Issue by bengalih** [Xentrk/nvram-save-restore-utility#2]
I realize the nvram-user-sample.sh is provided as a "sample", but even so, I thought I would report this.

The tar command at EOF shows:

`echo "Creating nvram-backup-$1.tar.gz"
tar -cvf "$cwd/backup/nvram-backup-$1.tar.gz" "$cwd/backup/nvram-restore-$1.sh" "$cwd/backup/jffs-$1"
`
It states it is creating a gz(ipped) tar file, which would indicate to the end user that it is a compressed file.  

However the tar syntax excludes the "z" parameter that would actuall compress the file.

Either the "z" parameter should be added to the tar command, or the file extension of the created file should be simply ".tar" and not ".tar.gz"

**Comment by Xentrk** [comment]
Thanks for the good feedback. I have push an update to add the z option to the tar command.
