### ISSUE TITLE
nvram-user.sh expects incorrect parameter

### ISSUE THREAD

**Issue by bengalih** [Xentrk/nvram-save-restore-utility#3]
Again, I realize this is a "sample" script, but I think this needs correction/clarification.
The nvram-user.sh expects single parameter in the yyyymmddhhmm_MODEL-macid format.

However, the nvram-save.sh script is actually passing it with a leading dash (i.e. "-yyyymmddhhmm_MODEL-macid").

This causes the user script to fail to process.

Either the format accepted by the user script needs to change, or the main script needs to omit the leading dash.

```
nvram-save.sh: Complete: User NVRAM saved to /tmp/mnt/flash_drive/nsru/backup/nvram-restore-202002251419_RT-AC68U-4C30.sh

nvram-save.sh: Complete: JFFS directory saved to /tmp/mnt/flash_drive/nsru/backup/jffs-202002251419_RT-AC68U-4C30

+ sh /tmp/mnt/flash_drive/nsru/nvram-user.sh -202002251419_RT-AC68U-4C30

ERROR: /tmp/mnt/flash_drive/nsru/backup/nvram-restore--202002251419_RT-AC68U-4C30.sh does not exist. No file to tar.

+ logger -s -t nvram-save.sh Complete: Processed user exit script /tmp/mnt/flash_drive/nsru/nvram-user.sh
```

**Comment by Xentrk** [comment]
Thank you for reporting the issue and sorry for the delay. I have patched the code to fix the dash issue.
